### ISSUE TITLE
Counter does not start (Time Tracker 0.0.19 / Nextcloud 15.0.7)

### ISSUE THREAD

**Issue by gdudas** [mtierltd/timetracker#1]
Hi,

the counter does not start (Time Tracker 0.0.19 / Nextcloud 15.0.7):

![timetracker_issue](https://user-images.githubusercontent.com/24443023/57072097-cb3eb480-6cdc-11e9-8dbc-b7cae7d3f416.PNG)

**Comment by puthre** [comment]
What browser do you use?

**Comment by gdudas** [comment]
I use Google Chrome 73.0.3683.103. I did try with Firefox 66.0.3, and I have the same issue. 

Nextcloud is installed from official Docker image (nextcloud:15.0.7-apache).

**Comment by puthre** [comment]
From your screenshot it seems that the counter is not even displayed. This can happen if the request to get the data to populate the page fails. You can try to see how the request fails using the developer tools or maybe try to reinstall the app as it might not have been installed properly.

**Comment by gdudas** [comment]
You are right, I get back Internal server error.

**Comment by reinerj** [comment]
Can you please test with the latest release 0.0.26. Another problem reported fixed this issue

Thanks
