### ISSUE TITLE
Dashboard and Report show only one project

### ISSUE THREAD

**Issue by ftastisch** [mtierltd/timetracker#10]
The Dashboard and report show a false summary of time tracked, e.g. there is only one project and customer shown in the dashboard, although several were tracked. Same for the report, only when filtered for specific customers/projects, the correct summed time is shown.
Running on NC 15.0.9 and TT 0.0.29.

**Comment by reinerj** [comment]
We will have a look at this issue asap and will fix it. Sorry for inconvenience

**Comment by ftastisch** [comment]
No problem, thank you for the helpful tool!
Please let me know if I can be of any help.

**Comment by puthre** [comment]
Hi, I have a couple of questions:
Is the database backend mysql or postgresql?
Is your user in the admin group?
Also if it's possible some screenshots with the good and bad reports would help (dashboard uses the same backend as the reports).

**Comment by ftastisch** [comment]
Hi!
Sure:
- database is MariaDB
- which admin group do you mean? Linux?
- Screenshots would take a while to remove information. What I noticed looking at the report:
  - there are now two rows, one for yesterday and one for today.
  - both show the sum of each day, but only one activity (its not the first activity of each day), a project that does not correspond to the project selected for the activities, and a client that does not correspond to neither.
  - project and client are linked correctly in the projects overview however.
  - when I select only one project to be shown in the report, it seems to work, two projects as well in the cases I tested, but from three projects up some are "lost" and only two are shown in the report, although each on its own will show the correct summed time

**Comment by reinerj** [comment]
We will publish a new release which should fix your problem reported. In case you still have problems please reopen.

Thanks

**Comment by ftastisch** [comment]
Hi!

I think there is still a bug hidden somewhere:
- Dashboard: Still only shows one client and one project.
- Report:
  - #: one row per day, so that seems correct
  - Name: activities listed also seem to be correct
  - users: currently using it alone, so only me and no way to check whether someone "is missing"
  - project: only one project is shown
  - client: several (and correct) clients are shown

I hope this helps.

**Comment by reinerj** [comment]
Thanks, we will check it again

**Comment by puthre** [comment]
Is this still happening with the latest version?

**Comment by ftastisch** [comment]
Hi!

It seems to working correctly now. Thanks!
