### ISSUE TITLE
Add / change allowed users

### ISSUE THREAD

**Issue by jjanarnava** [mtierltd/timetracker#100]
In your app one can find the table of projects with the allowed users. However editing the project does not allow to edit the allowed users. At the other hand my allowed user does not show up for any project I have created.

**Comment by Gunnar-GO** [comment]
You must set the corresponding project to locked to get the users inputbox.

Then the projects will be shared.

**Comment by jjanarnava** [comment]
I am very sorry, I missed to respond. But thank you for the Tipp Gunnar!
