### ISSUE TITLE
Nextcloud 21 compatibility

### ISSUE THREAD

**Issue by AS-dh** [mtierltd/timetracker#101]
I was warned before updating to nextcloud 21, but often just "enable untested app" would do. Not this time, however.  I've started heavily using Time Tracker to track my word and replace toggl, so I hope this can / will be fixed soon.
Thanx for the great work!

**Comment by AS-dh** [comment]
Oops, sorry, my fault. It does work. It was not enabled yet!

**Comment by aproposnix** [comment]
It's still an issue though because the version needs to be bumped. We shouldn't see "enable untested app".
