### ISSUE TITLE
Editing interval times across DST change yields wrong results

### ISSUE THREAD

**Issue by kralan** [mtierltd/timetracker#103]
Steps to reproduce:
1. Have an old entry in the timer view entered with CET in effect (e.g. 2021-03-01 15:00-16:00)
2. Try to edit the entry with CEST (DST) in effect, e.g. on 2021-04-02 to alter the interval to **15:00-17:00**
3. After closing the edit dialog, the interval will show as **14:00-16:00** in the timeline.

**Comment by mtierltd** [comment]
This should be fixed in our latest version.
