### ISSUE TITLE
[Bug] Details are cut in Report

### ISSUE THREAD

**Issue by Gunnar-GO** [mtierltd/timetracker#107]
By generating detailed reports i recognised that, my detailed descriptions are completely cut. 

My details looks like this way:
* DHCP corrected
* VPN reworked
* Server Updated

but in report the column Details only shows
`
*
` 

May the EOL-Check will be confused? An Report with Multiline, etc. would be awesome.

**Comment by Gunnar-GO** [comment]
The edit/bugfix doesn't change the behavior.

**Comment by ChornHulio** [comment]
I don't get it :thinking: Why was the issue closed and the PR merged, even if @Gunnar-GO said the fix doesn't work? Was it working on your machine, @mtierltd ?

**Comment by mtierltd** [comment]
> I don't get it  Why was the issue closed and the PR merged, even if @Gunnar-GO said the fix doesn't work? Was it working on your machine, @mtierltd ?

The commit is a correct bugfix. If you want to see the details in the report, you have to group by None, None, None, because otherwise aggregation is on, and the details column would be kind of useless, because
all the information would be integrated into one field.

**Comment by Gunnar-GO** [comment]
Sure, the changes are correct they fix an incorrect set, but **it didn't fix the reported bug**. 

As i said before. As stated this bugreport should not be closed, it is simply not solved.

**Comment by mtierltd** [comment]
There is nothing to solve, if you would like to have the details in the report, you have to set Group by to None, None, None.

**Comment by Gunnar-GO** [comment]
I just want not empty informationblocks. 'cause if they don't deploy Information they are useless/dropable. 
![image](https://user-images.githubusercontent.com/24938625/120063568-081a3880-c068-11eb-8b1d-645f81e652f0.png)

You're right, if i group by none/none/none the first few letters apear, even that they don't respect line-break, etc. (seems another topic). The content is cut by `overflow:hidden`.

![image](https://user-images.githubusercontent.com/24938625/120063687-ba520000-c068-11eb-997a-9ba09c4395b4.png)

But i see not much sense in why the group affects the details, in form that they drop all information. Why should group, filter and time trash/delete the details. In my oppinion it is unexpected behavior so this bugreport.

_By detail, why every line repeats the width and height declaration if they had class- and field-names? (i assume, in the css code is written in the loop?) And why is the table build by individual div-inline-blocks and not by table? (Maybe 'cause filtering? dunno.)_
