### ISSUE TITLE
Report output of entry details

### ISSUE THREAD

**Issue by codeHorse87** [mtierltd/timetracker#113]
Hi,

With release 0.0.56 the json and csv report format contains a *details* field. 
I'd expect this field to be filled with the entry details. However, this is not the case and the details fields contains asterisk values "*" instead.
Are there any plans to include the details of entries in the report formats?

Best,
codeHorse

**Comment by Gunnar-GO** [comment]
i asked the same ... https://github.com/mtierltd/timetracker/issues/107

if all filters are set to none the content is shown , my ask why (cause it looks like a bug for me) is still open.

**Comment by codeHorse87** [comment]
Hi @Gunnar-GO thanks for the mentioning. AS per the implementation explained it make sense that the grouping will always remove the detail information from the report. Using the filters works just fine. I'm closing the issue as for me resolved
