### ISSUE TITLE
Exception: Could not extract app timetracker

### ISSUE THREAD

**Issue by ovpc** [mtierltd/timetracker#117]
From log when updating to 0.0.59 from 0.0.58 NC 20.0.9

{"reqId":"YMyDTipmy28bFsI7@jVRbgAAFhM","level":3,"time":"2021-06-18T11:28:23+00:00","remoteAddr":"xxxxxx","user":"x","app":"core","method":"GET","url":"/index.php/settings/apps/update/timetracker","message":{"Exception":"Exception","Message":"Could not extract app timetracker","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Installer.php","line":198,"function":"downloadApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameter replaced ***",false]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":532,"function":"updateAppstoreApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"updateApp","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"updateApp"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"updateApp"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","updateApp",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"appId":"*** sensitive parameter replaced ***","_route":"settings.AppSettings.updateApp"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/update/timetracker"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/Installer.php","Line":297,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":"20.0.9.1","id":"60cc83659d42f"}

**Comment by mtierltd** [comment]
Hi

The issue has been fixed. Please give it a couple of hours for the nextcloud app server to refresh.
