### ISSUE TITLE
Dark mode is unclear

### ISSUE THREAD

**Issue by jaywink** [mtierltd/timetracker#12]
Thanks for the great app! Started using it instead of Toggl.

I recently switched to the new Nextcloud dark mode. The time tracker is a bit difficult to use with the dark mode, could do with some inverting of colours.

![Selection_227](https://user-images.githubusercontent.com/1174866/62032879-67e8f380-b1f3-11e9-9201-ae5d5908b1a2.png)

**Comment by reinerj** [comment]
Hi,

we never tested with dark mode :( We have to adjust this ... Thanks for the report

**Comment by puthre** [comment]
Please try with the latest version

**Comment by jaywink** [comment]
Great thanks @puthre looks much much better now!
