### ISSUE TITLE
[bug] Error by save Project with Tags

### ISSUE THREAD

**Issue by AlexandersWebdesign** [mtierltd/timetracker#120]
Wenn man Tags zu einem Projekt hinzufügen möchte bekommt man beim Speichern den Fehler "Error". Also können keine Tags mehr zu den Projekten gespeichert werden.

**Comment by nicoletflr** [comment]
I had the same experience

**Comment by nmolinski** [comment]
Yes. I can confirm.
1. Create a project. 
2. Lock it
3. Assign Users to it
4. Assign pre-created Tags to it
5. Hit "Edit Project"

"error" popup message shows.

**Comment by mtierltd** [comment]
fixed by 33f048098e24f1f89e21fdadcfad7da064715acc and release 0.0.65
