### ISSUE TITLE
[bug] Assigned users are lost when editing a project

### ISSUE THREAD

**Issue by AlexandersWebdesign** [mtierltd/timetracker#121]
When editing a project, the assignment to the employees is always deleted and must be reset each time.

**Comment by tigrrr** [comment]
Just confirming this bug makes the thing very unusable..

**Comment by mtierltd** [comment]
I have not been able to reproduce this issue so please provide more information
regarding your nextcloud release, database backend and a list of steps to reproduce.
Thank you

**Comment by kralan** [comment]
I can provoke the issue by executing the following steps:

1. Create a new project, name it "test"
2. Check that the project "test" exists and has the currently logged in user in the column "allowed users"
3. Click into the row diplaying the new project "test" to edit it
4. In the edit dialog, change the name to "test1" and click "Edit project"
5. Observe that the project is renamed to "test1" but has an empty column "allowed users"

I don't see any possibility to edit the values of "allowed users" or "allowed tags".

**Comment by mtierltd** [comment]
Hi

I've taken the steps you described and still could not reproduce the issue. What database backend are you using?

**Comment by tigrrr** [comment]
Hi, I can confirm the issue via the same steps that kralan described above. The problem is that if i change any of the project properties, the field allowed.users is cleared. It would make sense to add allowed.users as an editable field. The backen specs are: 
PHP 7.4.3, Database pgsql:PostgreSQL 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit. Nextcloud version: 22.0.0 (stable).

**Comment by kralan** [comment]
My database backend is mariadb 10.5.10, php7.4-mysql 7.4.21, nextcloud 22 on a debian bullseye system

**Comment by mtierltd** [comment]
Are you on the latest version of timetracker?

**Comment by tigrrr** [comment]
I was on 0.0.62, have updated to 0.0.64 and the issue hasn't changed after
the update..

**Comment by kralan** [comment]
I am at 0.0.64 right now, the problem has been present at least since 0.0.59, but I can't tell when it started for me, I don't edit my projects that often.

**Comment by kralan** [comment]
By inspecting the code I found out that there **is** a possibility of editing the allowed users and tags. Ticking the "locked" checkbox to edit is not exactly intuitive.
But I still cannot edit the allowed users - clicking in the respective field says "The results cannot be loaded".
Could this be related to the lost users problem?
![image](https://user-images.githubusercontent.com/10532729/127315845-9f2237dd-2899-4dc3-beff-c8d0399c2d4c.png)

**Comment by mtierltd** [comment]
Could you please upload your nextcloud logfile from the time when the results could not be loaded message appears?

**Comment by kralan** [comment]
This is all I could get, I hat to set the log level to 0=debug to obtain any messages at all. It is an excerpt of the minute I tried to set the allowed users. The command was `journalctl --identifier=Nextcloud  --grep=timetracker`.

[nextcloud_timetracker.log](https://github.com/mtierltd/timetracker/files/6913507/nextcloud_timetracker.log)

**Comment by kralan** [comment]
I noticed that in _projects.js_, all uri constructions are wrapped in `OC.generateUrl()`, with one exception being the generation of the request for the list of users. This could explain why it does not work for me (I have nextcloud in a directory under webroot, behind a reverse proxy) but works for others who have nextcloud installed in root locally.

**Comment by kralan** [comment]
I split out the problem with obtaining a list of users into a separate issue #144.

**Comment by kralan** [comment]
I don't see how this issue is resolved. The part of the problem split out as #144 is solved.
Still, the original problem persists:
- when editing a project the list of allowed users is cleared (this may be intended or not)
- when the list of allowed users is empty, the project cannot be used by any user, be it locked or not (this most probably is not intended)
