### ISSUE TITLE
24 hour clock

### ISSUE THREAD

**Issue by mrtxmrtx** [mtierltd/timetracker#126]
am/pm is uncommon in many countries. Optional switching to 24-hour time would be helpful.

**Comment by kralan** [comment]
I **do** have 24-hour times in Time Tracker, so it is not entirely impossible.
Try setting your locale in _Settings/Personal/Personal Info/Locale_ or set the local your browser is running under.

Still, date formats are inconsistent, I have dd/MM/yy in Timer view and both dd/MM/yy and yyyy-MM-dd in Reports, neither of which matches my set locale.

**Comment by mtierltd** [comment]
Hi

5a0d2457a1b56a429a02e8a2ed08ca68d10c0a23 implements better locale handling, so please
go ahead and test it.

Thank you

**Comment by kralan** [comment]
Thank you, date formatting works for me with the exceptions mentioned in the commits.

**Comment by mrtxmrtx** [comment]
Works for me too now, thank you. I cannot say something about the machine I experienced it with because it is not in my reach for the next months.
