### ISSUE TITLE
Can't create projects -> Pop-Up stating "error"

### ISSUE THREAD

**Issue by jnParis** [mtierltd/timetracker#143]
TimeTracker seems like a very nice tool! 

Unfortunately I can't create projects at the moment.
When I try to create a new project a pop-up states "error" without any further result.

Environment:
- TimeTracker 0.0.71
- Nextcloud 21.0.4

What works:
- Creating Clients
- Creating Tags
- Use Timer, Dashboard, etc.

What does not work:
- Creating Projects

**Comment by mtierltd** [comment]
Hi

What database backend are you using?

**Comment by jnParis** [comment]
Hey,

I'm using a Synology Diskstation with the official MariaDB 10 app (10.3.27-1037)
Just opened the database with phpmyadmin and found the timetracker tables. oc_timetracker_project exist but is still empty.

**Comment by mtierltd** [comment]
Please try our latest 0.0.72 release.

**Comment by jnParis** [comment]
Just checked: Same issue with nextcloud 22.2 and TimeTracker 0.0.72

**Comment by mtierltd** [comment]
Please send us your nextcloud logfile with the error message generated by timetracker.

**Comment by jnParis** [comment]
Here is the log attached. As it states something with colors I tried to choose different or none color but it never worked. (path and username changed in log file)

[timetracker.log](https://github.com/mtierltd/timetracker/files/7273168/timetracker.log)

**Comment by mtierltd** [comment]
Can you show me the schema of your oc_timetracker_project table? It seems you are missing a column.

**Comment by jnParis** [comment]
id | name | client_id | created_by_user_uid | locked | archived | created_at

**Comment by mtierltd** [comment]
Yes you are definitely missing a column from there. Please set `'debug' => 'true'` in your configuration file
and then run `occ migrations:status timetracker`.

**Comment by jnParis** [comment]
>> App:                                                timetracker
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OCA\TimeTracker\Migration
    >> Migrations Directory:                               mypath/apps/timetracker/lib/Migration
    >> Previous Version:                                   000000Date20210719124731
    >> Current Version:                                    000001Date20210719192031
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     000001Date20210719192031
    >> Executed Migrations:                                2
    >> Executed Unavailable Migrations:                    2
    >> Available Migrations:                               2
    >> New Migrations:                                     2
    >> Pending Migrations:                                 None

**Comment by mtierltd** [comment]
For some reason, you are missing the `color` column and that is why
you get the error, however the database migrations are up-to-date.

I suggest you just add the missing column.

`ALTER TABLE oc_timetracker_project ADD COLUMN color VARCHAR(7) NOT NULL DEFAULT '#ffffff';`
