### ISSUE TITLE
Download error in NC 16 CURL/TSL

### ISSUE THREAD

**Issue by robert-nezz** [mtierltd/timetracker#16]
Hello.

I'm getting the same issues as described in #13. This happens **only when downloading the Time Tracker**. All other apps are downloading fine. I was trying to investigate the issues using manual curl.

`curl -v https://mail.nerd.hu/timetracker.tar.gz`

This get the same error as in NC:
```
 TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS alert, protocol version (582):
* error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
* Closing connection 0
```

I have tried to force curl to use lower TLS version 1.2, 1.1, 1.0, nothing worked for me:

`curl -v --tls-max 1.2 https://mail.nerd.hu/timetracker.tar.gz`

Only thing that passed without issues is using plain HTTP:

`curl -v http://mail.nerd.hu/timetracker.tar.gz --output timetracker.tar.gz`

It seems to be an issue with TSL 1.3 (curl autodetect version) on the mail.nerd.hu server although seems to working fine in browser. Hope this helps in any way.

**Comment by paulcalabro** [comment]
I'm getting the same error with v0.0.34.

**Comment by frankgerhardt** [comment]
I can't install it on NC 16.0.4.

**Comment by paulcalabro** [comment]
I can't install it on NC 17.01.

**Comment by vitortle** [comment]
I can't install it on 17.0.2.

**Comment by reinerj** [comment]
But what is the error. You need to provide a little more information

**Comment by vitortle** [comment]
When clicking in "Download and activate" (or something similar. Mine is in Portuguese-BR) at the Apps section of the nextcloud (17.0.2.), the error comes inside a yellow box: 
`cURL error 28: Operation timed out after 30000 milliseconds with 2719047 out of 2827051 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by reinerj** [comment]
We can't reproduce the problem. Can you try again please
