### ISSUE TITLE
Dashboard View: All Time is summed up under one client

### ISSUE THREAD

**Issue by unclesam87** [mtierltd/timetracker#18]
Hello,

i get following problem:

I got several clients, all with some time spend on their projects,
the dashboard sums them up under one client in the outer circle, it is the client with the most time spend...

Nextcloud 16
Timetracker 0.0.34
Ubutnu 18.04 LTS
Nginx updated
PHP-fpm

**Comment by puthre** [comment]
Are you using mysql or postgresql?

**Comment by unclesam87** [comment]
mariadb so mysql

**Comment by puthre** [comment]
Are your projects assigned to the respective clients in the projects page?

**Comment by puthre** [comment]
Never mind, I think I've reproduced and fixed it. Can you please try with the latest master ?

**Comment by unclesam87** [comment]
thx that fixed it:)
