### ISSUE TITLE
[Feature Request] Please, put the details of tasks into report.

### ISSUE THREAD

**Issue by pgavro** [mtierltd/timetracker#183]
Hi, thanks a lot for your app/tool. It's very useful for me. I would like to ask  you for a small feature in the report. Can you put the text of details of the tasks into reports? Actually, in report (column Details) are the stars (*) in-place . Thanks a lot. 
![image](https://user-images.githubusercontent.com/61777513/176848409-52773cfa-dbb4-442e-af6f-434030bcda90.png)

**Comment by mtierltd** [comment]
Hi

To get details there, you have to disable all group by filters. Set all three to None.
