### ISSUE TITLE
Using the play icon to continue an activity is broken

### ISSUE THREAD

**Issue by kralan** [mtierltd/timetracker#194]
Using the play icon on a line in timer view to continue an activity is broken since 0.0.76.
**Before 0.0.76 it used to:**
Stop the currently running activity, start a new activity with the entries copied from **the entry the play icon was clicked on**.
**Now it does:**
Stop the currently running activity, start a new activity with the entries copied from **the most recent entry**.

**Comment by printplaatreparatie** [comment]
A small addition: The hover-over text always displays "Start", even when the button shows the rectangular stop icon.

**Comment by mtierltd** [comment]
@Hawiak i think it was your baae5a744eb1c937f38b2b92e1b6843de525c62d commit that broke this.

**Comment by Hawiak** [comment]
@mtierltd ah, it's been a while since I made that. I'll try to look into it
 @kralan could you please elaborate further on the issue you're experiencing? I'm not quite sure what is going wrong at this moment.

**Comment by kralan** [comment]
@Hawiak the problem is as follows:

The goal is to restart or continue a previously recorded activity without having to enter all data manually. There is a play icon to the right of every timer entry o accomplish this.

1. You are in timer view and have a few activities recorded:

topDescription topProject topTag topCost topStartTime-
otherDescription otherProject otherTag otherCost otherTimeInterval
clickedDescription clickedProject clickedTag clickedCost clickedTimeInterval |> <--- click here

2. you click on the play icon to the right of the clickedXXX line

3. results
expected result (this is what you got up to version 0.0.75:

clickedDescription clickedProject clickedTag 0.00 now- 
topDescription topProject topTag topCost topStartTime-now
otherDescription otherProject otherTag otherCost otherTimeInterval
clickedDescription clickedProject clickedTag clickedCost clickedTimeInterval

observed result (this is what you get with 0.0.76):

noDescrption topProject topTag 0.00 now- 
topDescription topProject topTag topCost topStartTime-now
otherDescription otherProject otherTag otherCost otherTimeInterval
clickedDescription clickedProject clickedTag clickedCost clickedTimeInterval

In addition to that, after editing the new runnig activity to desired values, after clicking stop the line gets messed up with wrong values, but haven't identified any pattern yet.

**Comment by Hawiak** [comment]
I believe I have found and fixed the issue. I've opened a PR.

**Comment by printplaatreparatie** [comment]
PR #199

**Comment by mtierltd** [comment]
fixed by 14d60729f3588b86a742c24b5737e6e949347bfc
