### ISSUE TITLE
Export the precise time

### ISSUE THREAD

**Issue by unclesam87** [mtierltd/timetracker#20]
Hey,
would it possible to add an export of the precise time? for my clients it is important to see at which time of day it worked.
Thank you

**Comment by puthre** [comment]
Where do you need the precise time to show up?

**Comment by unclesam87** [comment]
On the report page would be good:)

**Comment by puthre** [comment]
All reports are currently aggregated so you can't have precise times.
My understanding is that you would need to export the raw work items entries?

**Comment by unclesam87** [comment]
excaktly - so i can use it to print out an paper with my raw work times

**Comment by puthre** [comment]
Starting with 0.0.38 you should be able to select "none" at all the reports group by fields and that would export all the entries with the exact starting times.
