### ISSUE TITLE
Donut graph appears twice

### ISSUE THREAD

**Issue by fpPierre** [mtierltd/timetracker#208]
I currently facing two donut graphs that shows the same information. 
I guess that it should reflect on different time frames but I´m not convinced.

Can somebody confirm that there should be two graphs?

**Comment by printplaatreparatie** [comment]
One should be for projects, but is now incorrectly displaying the clients.

**Comment by printplaatreparatie** [comment]
One is displaying the time, the other the costs at my dashboard.

**Comment by fpPierre** [comment]
Ah ok, got it. Thank you
