### ISSUE TITLE
timetracker breaks with NC26

### ISSUE THREAD

**Issue by kralan** [mtierltd/timetracker#210]
timetracker uses the deprecated API OCP\AppFramework\Db\Mapper which was removed with NC26.
See https://github.com/nextcloud/server/issues/34692 and https://github.com/nextcloud/server/pull/34490

**Comment by elpraga** [comment]
I've noticed the same (I believe) issue discusses about the [Music app](https://github.com/owncloud/music/issues/1050#issuecomment-1478475738) @mtierltd @kralan . Could a similar solution work for **Timetracker** as well?

**Comment by JoshuaPettus** [comment]
Should note Music has the added issue of maintaining compatibility with Owncloud and shipping its own version of mapper is the only way to allow both.

**Comment by blizzz** [comment]
> Should note Music has the added issue of maintaining compatibility with Owncloud and shipping its own version of mapper is the only way to allow both.

It can be seen as a quick fix to establish compatibility in a short time, but eventually the migration to QBMapper should be done. Mapper is deprecated for a long time already.
