### ISSUE TITLE
Created timeline does not appear until reload

### ISSUE THREAD

**Issue by Chralu** [mtierltd/timetracker#22]
Hi,

I'm encountering a small issue on **v0.0.34**.

_Here is the steps to reproduce issue :_

1. Go to screen `apps/timetracker/timelines`
1. Click on **Export Timeline CSV**

_Expected Behavior :_

The table **Exported Timeline statuses** refreshes to show the new Timeline.

_Actual Behavior :_

You have to manually reload the page to refresh the table.

Thanks a lot for your good work 👍

**Comment by puthre** [comment]
Could not reproduce this on 0.0.36. Timeslines list refreshes automatically after export.

**Comment by reinerj** [comment]
No feedback. When there is still this issue please reopen
