### ISSUE TITLE
Nextcloud 30 Support - I am willing to do the work

### ISSUE THREAD

**Issue by thisiszeev** [mtierltd/timetracker#226]
I am rather familiar with PHP and getting the hang of VueJS rather quickly. But I am a rookie with developing for Nextcloud.

If someone can point me in the right direction for where I can get documentation for what is depreciated and what is current on the Nextcloud 29/30 API, I am confident I can bring this app upto support Nextcloud 30.

**Comment by mtierltd** [comment]
Hi

You can find all the information in the developer manual at https://docs.nextcloud.com/server/latest/developer_manual/

The rest of the deprecated functions can be found in the release notes of each release.

And of course, contributions are always welcome! :)

Thanks
