### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by IpeTek** [mtierltd/timetracker#23]
I'm on 17.0.1. Using Hetzner's re-labeled NC, the Storage Share. 

When trying to install Time tracker I get "A problem occurred during the request. Cannot install."

I've had no problems installing the other 30 to 40 apps. Please, help.

**Comment by mraitisoja** [comment]
I have the same issue, Hetzner StorageShare and can't install this app. Others work ok so far.

**Comment by reinerj** [comment]
Do you have any more information for us? We just tested it again on a test system without any problems

**Comment by richard73g** [comment]
I seem to have a similiar problem with my nextcloud installation on ubuntu 18.04.
Error message: cURL error 35: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

![grafik](https://user-images.githubusercontent.com/58692254/70436525-ce2b3000-1a89-11ea-9e98-d6e0d47340d5.png)

**Comment by EmJotGeh** [comment]
Same Error here...

**Comment by reinerj** [comment]
Can you try again. The package was just moved to  new location

**Comment by richard73g** [comment]
Works fine for me now. 
Thank you for your help.

**Comment by reinerj** [comment]
No idea why but this problem was clearly related to a specific OS
