### ISSUE TITLE
Time tracker doesn't set correct timezone when retrieving work intervals

### ISSUE THREAD

**Issue by zeroepix** [mtierltd/timetracker#26]
Heya, there seems to be a bug in the "day-name" date when it loads the work intervals from the server. 

I live in the UTC+11 timezone, and it records the individual times faithfully, but the day-name isn't converted to my local time before being set in the outgoing json. 

I think I found the cause and have a fix I've been using but I don't know how to make a generic solution since the user's timezone doesn't seem to be recorded in the database, unless I've missed it. 

lib/Controller/AjaxController.php, from this:

```
public function workIntervals() {  
	$i = 0;  
	$tryIntervals=[90,180,365,365*5];  
	do {  
		$l = $this->workIntervalMapper->findLatestDays($this->userId,$tryIntervals[$i],0);  
		$i++;  
	} while ((count($l) == 0) && ($i < count($tryIntervals)));  
	$days = [];  
	foreach ($l as $wi){  
		//$dt = date("d/m/Y", $wi->start);  
		$dt = date("D, j M", $wi->start);  
```
To this:

```
public function workIntervals() {
        $i = 0;
        $tryIntervals=[90,180,365,365*5];
        do {
            $l = $this->workIntervalMapper->findLatestDays($this->userId,$tryIntervals[$i],0);
            $i++;
        } while ((count($l) == 0) && ($i < count($tryIntervals)));
        $days = [];
        $tz_offset = timezone_offset_get(timezone_open('Australia/Melbourne'), new \DateTime());
        foreach ($l as $wi){
            //$dt = date("d/m/Y", $wi->start);
            $dtz = $wi->start+$tz_offset;
            $dt = date("D, j M", $dtz);
```

It's possible to get the system timezone from the php.ini I guess, but it might be better to just save the offset with the work interval and add it when it comes out.

**Comment by puthre** [comment]
All the timestamps are converted and stored on server on UTC timezone. 

We don't convert back to user  timezones when showing the data as it might be confusing for users that see or share the same data but are from different timezones.

**Comment by zeroepix** [comment]
Yes I saw and figured the same thing, some users may not want the server's timezone.

Why not just save the offset with the work interval? It's coming in with the Ajax data already, you can default it to 0 to imply UTC, then save the offset there. When it's sending data out, just add it to:
```
$dt = date("D, j M", $wi->start); 
```
becomes
```
$dtz = $wi->start + $wi->tzoffset;
$dt = date("D, j M", $dtz); 
```
since that is the only variable that has a problem. The other stuff is converted to the proper timezone back in the browser, but this one is done here.

Alternatively, I guess you could change the javascript code to covert it there, and just send the timestamp here.

**Comment by puthre** [comment]
I think that saving the timezone offset will not solve the issue as it would show wrong values when accessing the data from a different timezone.
I guess we could have a configurable feature to enable the conversion of the server timestamps to the local browser timezone.

**Comment by zeroepix** [comment]
How interesting...yes you're right, if you travel it will show your home timezone.

How about delegating the responsibility to convert day-name to text to the browser? Would that work? e.g.:

``` $dt = date("D, j M", $wi->start);   ``` 

becomes

``` $dt = $wi->start; ``` 

and in timer.js you just convert dayName to a locale date?

**Comment by zeroepix** [comment]
I see why this is more complicated than it first seems. Using 
```$dt = $wi->start;```
works with no timezone adjustment necessary in the browser, but it undoes all grouping by day which is done by the AjaxController. It will need to be grouped in timer.js instead of the AjaxController.

**Comment by floogy** [comment]
This may be a good client-side solution. The Nextcloud Calendar app also stores everything in UTC, does not record the User time locally, and displays the offset according to this JS:

https://github.com/pellepim/jstimezonedetect/

This all happens in the browser and doesn't depend on GeoIP or similar. It's a 12kb `jstz.min.js` file.

**Comment by smatthie** [comment]
It would be good to use a similar solution as the calendar app, also for consistency, not reinvent the wheel and confuse the users with a different approach...

The calendar app allows you to use "automatic" (which apparently uses the system time zone) or set it manually to a different time zone and that seems a good solution for me. 

In any case, showing only UTC is confusing and not so useful for those of us who are not on UTC, as one normally needs the time per actual local working day.

**Comment by mjensen61** [comment]
Love your work.  This is a very attractive app: Possibly a related issue.  I am working in AEST (GMT +10hr)   Entries early each day appear under that date of the day before in the Timer entries.  Times should be displayed in the user's Local Timezone.  

I note that for the purposes of this exercise the timezone may irrelevant as the time entries are relative between start and finish so rather than store them in UTC they could have been be stored in local time.  But I guess that bridge has been crossed.

I'm entering the times manually using your datetime widget.

**Comment by LovesTha** [comment]
> Love your work. This is a very attractive app: Possibly a related issue. I am working in AEST (GMT +10hr) Entries early each day appear under that date of the day before in the Timer entries. Times should be displayed in the user's Local Timezone.

I ended ushered looking to reportthis same issue. We should probably start a different issue though
