### ISSUE TITLE
details not escaped properly when saving to database

### ISSUE THREAD

**Issue by zeroepix** [mtierltd/timetracker#27]
So I saved the below block as my "details" for one of my work intervals, so I wouldn't forget it later, but now it won't load properly. The new details for this work item stops at the opening single quote, and the title of the work item has become "start);$dtz = $wi->start+$tz_offset;..." so its breaking the js/html coming out.

```
Made these changes to timetracker/lib/Controller/AjaxController.php:
                                                                                         
                                                                                         
 $tz_offset = timezone_offset_get(timezone_open('Australia/Melbourne'), new \DateTime());
         foreach ($l as $wi){                                                            
             //$dt = date("d/m/Y", $wi->start);                                          
             $dtz = $wi->start+$tz_offset;                                               
             $dt = date("D, j M", $dtz);                                                 
```
I mean, it's PHP code, and it saved it faithfully, but it doesn't like reading it back out (using PostgreSQL). To fix it I just deleted it, but you should be able to paste that into details to replicate the issue.

**Comment by puthre** [comment]
Replicated and fixed.
