### ISSUE TITLE
Reports Tables does not show Name and Details value of Work Items

### ISSUE THREAD

**Issue by lewie** [mtierltd/timetracker#28]
Thanks for sharing this app. I like it very much!

My Versions:
Nextcloud 17.01
Time Tracker 0.0.39

![grafik](https://user-images.githubusercontent.com/5707426/71249136-cd618c00-231c-11ea-9151-012e7fd04dd1.png)

Reports Tables does not show Name and Details value of Work Items:
![grafik](https://user-images.githubusercontent.com/5707426/71249014-94c1b280-231c-11ea-9f35-51a5505afc88.png)

**Comment by puthre** [comment]
They don't show because they are grouped. 
There can be multiple work items with different names in that group

**Comment by lewie** [comment]
Ah OK, but is there a way to ungroup to see details in Reports? Or to show a sublist or array of strings in the fields Name and Details?
