### ISSUE TITLE
TimeTracker 0.0.4 cannot edit task discription

### ISSUE THREAD

**Issue by ovpc** [mtierltd/timetracker#30]
NC 17.0.2 on Buster 
Since TimeTracker update to 0.0.4 I can no longer edit details of tasks.
Or rather, I can edit and add details, but they dont get saved.

nc.log fills with

  | settype(): Invalid type at /var/www/nextcloud/lib/public/AppFramework/Db/Entity.php#110
-- | --

**Comment by puthre** [comment]
Is this on mysql or postgress?

**Comment by ovpc** [comment]
mysql

**Comment by Follpvosten** [comment]
I'm hitting the exact same issue, running NC 17.0.3 on FreeBSD 11, also on MariaDB.

I'd really like to get this fixed because I was very happy to find a timetracking tool for Nextcloud, but I don't know a whole lot of PHP (especially when it comes to the debugging process), so I'm afraid I might not be able to help...

**Comment by cliffalbert** [comment]
Same problem here on NC 18 on Debian 10 with PostgreSQL.
Seeing the same error with settype(),

**Comment by reinerj** [comment]
We are working on it. A fix will be ready asap.

Thanks
Reiner

**Comment by bwie** [comment]
Thank you very much for the excellent tool. I was looking for a good time tracking solution for a long time.
Unfortunately I have the same problem at the moment.

**Comment by puthre** [comment]
Fixed.

**Comment by zeroepix** [comment]
nice one, how do we pull it to the apps folder? Can it only be done through a version update in nextcloud?

**Comment by cliffalbert** [comment]
Looks like that fixed the issue for me :) 
Thanks!

**Comment by ovpc** [comment]
Yes, 0.0.41 works for me too, thank you!
