### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by fancycode** [mtierltd/timetracker#36]
To keep track of changes between different versions it would be great if you could tag releases.

**Comment by reinerj** [comment]
Will be done

**Comment by fancycode** [comment]
Why was this closed? I don't see any tags in the repository yet.

**Comment by puthre** [comment]
@fancycode We will tag new releases. There is no need to keep an issue open for this.

**Comment by fancycode** [comment]
I assumed it would be closed once you did the first tagged release and kept open as reminder until then, but ok :-)
