### ISSUE TITLE
Downloading Timelines does not work for me

### ISSUE THREAD

**Issue by manfredu** [mtierltd/timetracker#38]
I just get an empty window with empty html source, no error in browser console, no download file.

Tried with Vivaldi 2.11 and Firefox 73 (Ubuntu 19.10) and Chrome (Windows 10).

Nextcloud 17.0.3

**Comment by puthre** [comment]
Do you use postgresql or mysql?

**Comment by manfredu** [comment]
Database: 10.3.20-MariaDB

PHP version: 7.3.13

**Comment by puthre** [comment]
I was able to reproduce this when there is no data in the timeline. That is the "total duration" of the timeline you want to download?

**Comment by manfredu** [comment]
Here it happens all the time with different total durations.

**Comment by puthre** [comment]
Any errors in the logs when you try to download them?

**Comment by manfredu** [comment]
nextcloud.log:

{"reqId":"1ukYG1MviXXaI3jR6kPF","level":3,"time":"2020-03-08T09:05:08+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"PHP","method":"GET","url":"/apps/timetracker/ajax/report?name=&from=1581149107&to=1583654707&group1=project&group2=user&timegroup=day&filterProjectId=&filterClientId=","message":"settype(): Invalid type at /usr/local/www/nextcloud/lib/public/AppFramework/Db/Entity.php#115","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.125 Safari/537.36","version":"18.0.1.3"}

nextcloud_errors.log:

n/a

**Comment by puthre** [comment]
Is this still happening?

**Comment by manfredu** [comment]
Sorry, didn't notice the question.  

Yes, this is still happening here.

**Comment by bb** [comment]
Downloading timelines didn't work for us as well on NextCloud 21 on Postgres 13 using TimeTracker 0.0.56. I tracked it down to two reasons:

1. empty `client_name` in `oc_timetracker_timeline_entry` but column is defined as `NOT NULL`. Setting the client_name before insertion is currently commented out in https://github.com/mtierltd/timetracker/blob/master/lib/Controller/AjaxController.php#L967 (and just removing the `//` triggered another error which I didn't bother investigating).

2. Table `oc_timetracker_work_interval` allows `project_id` to be `NULL` but `oc_timetracker_timeline_entry` enforces `NOT NULL` for `project_name`. There was a single entry without project in our DB.

Both issues could be worked around by removing the `NOT NULL` constraints for `project_name` and `client_name` in `oc_timetracker_timeline_entry`.

**Comment by bb** [comment]
Update to my comment above: The automatic upgrade failed because it wanted to restore the `NOT NULL` constraints. So this time, I just updated the columns to have no NULL values instead of changing the schema.
