### ISSUE TITLE
When time tracker is running, if you refresh the page and stop the timer, it records it as no description

### ISSUE THREAD

**Issue by zeroepix** [mtierltd/timetracker#42]
I'm not sure if this is just unique to my instance (using chrome) or a common issue, but this is how to replicate:

1. In timer, fill in something for "what have you done?" box, e.g. "read emails". Click play to start it.
2. Notice the new timer in the list has the title you gave it (e.g. "read emails"), then refresh browser.
3. The timer box now says "what have you done?" again, but the timer is still running and the timer in the list still says the right title ("read emails")
4. Click stop, the page will refresh, and you will now have a timer in the list with the correct timings, but the title will be "No Description" instead of e.g. "read emails". 

You can click the timer and fix the name, but it would be better if the "what have you done?" box was populated from the last timer started, if it is still running.

**Comment by kralan** [comment]
Stopping the timer records the contents of the "what have you done" field at the time of the click as name of the job, even when the job already has a name. It would be better to keep an already existing name.

**Comment by kralan** [comment]
@puthre, thank you for looking into this annoying issue.
I haven't tired the code yet, but I'm afraid the fix won't do.
Your fix reads: "If the name in the entry field differs from 'no description' record this as the name for the item being stopped"
I believe a fix should read: "If the item being stopped has a name different from 'no description' record the name form the entry field as its name"

**Comment by puthre** [comment]
@kralan if you have a new name set in the name of work item field when you stop the activity, then that is the final name that the user wants to set to the work item in progress. If you don't have any (because of a refresh of the page for example) then the name that is kept is the initial one.

**Comment by zeroepix** [comment]
Why not just populate the empty text field with the name of the running timer?

**Comment by zeroepix** [comment]
Either way, just commenting to say thanks for fixing this super minor but huge quality of life improving issue.
