### ISSUE TITLE
Support for Nextcloud 19?

### ISSUE THREAD

**Issue by e-alfred** [mtierltd/timetracker#43]
Nextcloud 19 was released a few days ago, please publish a new release supporting it to the App Store.

**Comment by g-work** [comment]
I also would love a Nextcloud 19 release!

**Comment by mnestor** [comment]
I've been using the current version in 19 and not found any show stoppers. Just a timezone issue with the timer. It uses the right time but the day setting is UTC.

**Comment by stramag** [comment]
Please create a NC 19 version!
Because I love this app.....

**Comment by kelvan** [comment]
new version available now

**Comment by stramag** [comment]
Thank you the new version and your answer too! :-)
