### ISSUE TITLE
Allow to pick colors for projects

### ISSUE THREAD

**Issue by errnesto** [mtierltd/timetracker#45]
I think it would be a nice feature to be able to pick a  color for a project and then show a colored dot or line next to it in the timer / project selection etc. 

The dashboard looks nice but I almoast nerver care about the last 30days… but either about last month or 'unbilled hours'

Maybe also tags could benefit from colors but then the design and color combinations are getting a bit more complicated…

**Comment by puthre** [comment]
Aren't tags a generalization of colors?
