### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by tarpin** [mtierltd/timetracker#5]
Could you please add the possibility to define custom fields of entry. A custom field could have different types such as numeric or text fields, a drop-down list. It would be great if the field could be validated by regular expressions.
This would be useful when working with trackers (e.g. GitHub) - you can add an issue's ID.

**Comment by noseshimself** [comment]
I'm not that greedy but I would like to get a "Comment" or "Details" field to enter a longer text describing what I did.

**Comment by reinerj** [comment]
This is already assigned to a milestone

**Comment by noseshimself** [comment]
Which milestone is it and when do you expect to reach it?

**Comment by reinerj** [comment]
Next release, but we would also accept patches ;)

**Comment by noseshimself** [comment]
I was the person who wanted _one_ additional field for adding details, notes and remarks, not the freely configurable addition of user-defined fields 8-). That might be a usable intermediate step without serious implications for UI and database handling.

**Comment by puthre** [comment]
Now there is a new "details" field that also show up in the reports when there is no aggregation.

**Comment by reinerj** [comment]
No feedback since some time.
