### ISSUE TITLE
Where is the setting for the start of the Timer list?

### ISSUE THREAD

**Issue by uwedisch** [mtierltd/timetracker#51]
Currently the Timer list scrolls back for about 37 days, i.e. today Oct. 29th to Sept. 22nd.

Is there some setting to change that to scroll back for 60 days?
For example, I need to change project for Timer entries as of Sept. 9th because they are wrong.

**Comment by reinerj** [comment]
Hi,

we will have a look and come back asap

Regards
Reiner

**Comment by uwedisch** [comment]
Hello,
thank you for the immediate fix with 65db2de, but it is not working. Regardless of what I choose, I always only see the last 30 days.

**Comment by smatthie** [comment]
I see the same problem (the time selection doesn't work and it always shows the last entries).

It would also be useful to have a filter for projects and clients (like in the reports) etc. to make it easier to hunt down older entries one might have to change.
