### ISSUE TITLE
Feature request: Include exact start and stop times in CSV export, not only total duration

### ISSUE THREAD

**Issue by p-p-q** [mtierltd/timetracker#52]
Hello,
thank you for making this helpful app. It does almost everything I need to document the time and duration I have worked. The only further thing I need is fields for the start and stop dates/times in the exported CSV file. It could be a string in ISO 8601 format in order to include time zone information, e.g. 2007-08-31T16:47+00:00 for UTC. 
Could you maybe add this feature, or an optional setting to include this information, with a specified time zone or region? Thanks!

PS: So far, Time Tracker works fine for me in Nextcloud 20.

**Comment by puthre** [comment]
@p-p-q are you referring to reports export or timeline export?

**Comment by p-p-q** [comment]
@puthre I was referring to the reports export feature. In the generated CSV file, there are fields for the date (day only) and the total duration, but not for the actual points in time for starting and ending work. Thanks for the clarification

**Comment by puthre** [comment]
This might be implemented only for the case where the report you choose to export is not aggregated.

**Comment by p-p-q** [comment]
Thank you for implementing this!!
