### ISSUE TITLE
Setting for Start of Timer List isn't working

### ISSUE THREAD

**Issue by uwedisch** [mtierltd/timetracker#56]
Hello,
thank you for the immediate fix with 65db2de, but it is not working. Regardless of what I choose, I always only see the last 30 days.

_Originally posted by @uwedisch in https://github.com/mtierltd/timetracker/issues/51#issuecomment-723646659_

**Comment by zeroepix** [comment]
Are you on NextCloud 19+? When you click on a date and look at console there's a bunch of:
```
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```

If the developers are on version 18 the global jquery was still working afaik, so it would have worked in testing.

**Comment by zeroepix** [comment]
Mine shows 7 days and 30 days, but not beyond that.

**Comment by puthre** [comment]
@uwedisch  Are you referring to the Timer page?

**Comment by uwedisch** [comment]
Yes, I do so.
Someone sent me direct message that he assumes that the vendor used Nextcloud 18, but I'm using Nextcloud 19.

**Comment by smatthie** [comment]
This seems to work now in version 0.47. But I wonder why it's not using the same filters as the report and timeline view; for example yesterday and custom range are not there. Would it not be easier to use the same code in all three places?
