### ISSUE TITLE
Manual Entry Dialog

### ISSUE THREAD

**Issue by christianalles** [mtierltd/timetracker#58]
I noticed two things making manual entries:

First is a minor bug:
Manual entry form fields are not reset after adding an entry, so when you add another one you will have a prefilled form.
This is a bit irritating because the user could thing that he is editing the previous entry instead of creating another one.

The other is a suggestion to make manual entries more comfortable/quicker:
Instead of entering start date, start time hours, start time minutes, end date, end time hours end time minutes,
It might be quicker and more user friendly just to specify start date and a duration/time span in days, hours and minutes, where days/hours should be optional.
Thus an entry could be as quick as selecting a date, typing a name an entering a duration in minutes. This way we could enter the time part of the entry by specifiying 2 to a maximum of 4 values instead of 6. Also the calendar widget could be half as big.

Cheers

**Comment by smatthie** [comment]
Only duration would not be good for me, as I usually think in terms of "I started at 2:30 end finished at 4:15", and having to work out the duration first before being able to enter it would be a step in the wrong direction and make it more complicated.
Users probably have different preferences, so perhaps both should be possible: an end time and a duration field, and when you fill in one of those, the other is calculated.

**Comment by puthre** [comment]
I think the time interval should be reset when adding a new manual work item (not the name and description) and the popup window name should be changed to "Add work item".
The second issue, as @smatthie remarked, I don;t think will improve the experience,, users keep track of tasks as starting times and ending times, not as durations.
