### ISSUE TITLE
No real description / readme and no screenshots

### ISSUE THREAD

**Issue by DanielRuf** [mtierltd/timetracker#59]
I am missing a good readme with some description of the features and some screenshots.

The current readme file contains only informtion for contributors and not for users. Same at https://apps.nextcloud.com/apps/timetracker where no information is provided at all.

It would be great to have this so we can make some basic decisions before we try the app.

**Comment by LukeLR** [comment]
@DanielRuf See #73, feel free to review if you want to! ;)

**Comment by DanielRuf** [comment]
Closing as the linked PR is merged :+1:
