### ISSUE TITLE
Timer can't be started in 20.0.2

### ISSUE THREAD

**Issue by Gunnar-GO** [mtierltd/timetracker#60]
in Nextcloud Version 20.0.2 i can view, filter etc like a normal behavior.

if i try to start a timer it sets the icon to stop and 1 second later again to start. no entry is generated or given.

in the console theres several (more than a dozen times) warnings with: 
>  $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.

and 

>  The select2 library is deprecated! It will be removed in nextcloud 19.

sadly i can't go back to an older nextcloud version since features of other tools in actual version is needed.

**Comment by reinerj** [comment]
We will check this with priority

**Comment by puthre** [comment]
@Gunnar-GO It works fine for me on 20.0.2 (just upgraded today). 
What are you using mysql / postgresql?

Any messages / warnings in /settings/admin/overview ?
