### ISSUE TITLE
`#` breaks entry, project, client and tag names

### ISSUE THREAD

**Issue by LukeLR** [mtierltd/timetracker#68]
Hi everyone,
thanks for this great app! I really like it a lot, and started to use it in my daily life.

I noticed a bug that's not very urgent but makes me worry about input sanitization in general: A `#` character in the title of an entry, project, client or tag ends the string. E.g., if I enter `foo#bar` in the title of an entry and click "Edit work item" to save it, the title will just read `foo`, with the rest of the entered string missing starting from the `#`.

Is the input properly sanitized? Or might this point to the possibility of SQL injections etc.?

Thanks in advance for looking into this!
LukeLR

**Comment by Alexander-Zierhut** [comment]
Was able to reproduce this. Not in the description of a manual entry though. 
![image](https://user-images.githubusercontent.com/26348781/104513322-c4122400-55ef-11eb-94bf-850683c64e6b.png)

**Comment by puthre** [comment]
is this still happening? I think it was fixed when I fixed #39 . It was not about input sanitisation, it was about the name being sent in urls non urlencoded.

**Comment by Alexander-Zierhut** [comment]
> it was about the name being sent in urls non urlencoded.
That'S what I had in mind too. I'll give it a try.

**Comment by Alexander-Zierhut** [comment]
Can confirm. Is fixed now.
