### ISSUE TITLE
Overview for earlier time entries (start & end time)

### ISSUE THREAD

**Issue by jenskaesler** [mtierltd/timetracker#7]
Is it possible to add the functionality that you can see start and end date of an earlier time entry? This is acutally only visible in "timer" tab and in timer tab not all earlier entries are visible. In "reports" is it not possible to see the start and end date of an time entry. This is also not visible if you export the time entries into csv or json.

I need to say thanks for your great app! It is very useful to get an overview of my working times!! Thanks a lot!!

**Comment by reinerj** [comment]
Hi,

and thanks for the feedback. 

We could add this to the roadmap as a new function, yes,

**Comment by reinerj** [comment]
This should work now. Can you confirm. When it does not work as you want please reopen
