### ISSUE TITLE
Timer display continues to count after pressing stop

### ISSUE THREAD

**Issue by LukeLR** [mtierltd/timetracker#70]
I noticed that the timer continues to count up even after pressing start. Only after pressing start the next time, it gets reset. While this does not affect usability so much, it'll probably confuse unknowing users, especially as the entry title also does not get cleared after pressing stop. But the latter is probably a feature to some people that want to enter different entries with the same name, I guess.

I consider this one a bug, but again, probably not a very urgent one :)

**Comment by puthre** [comment]
What version was this tested against? Most of this part was reworked in the latest commits.

**Comment by manfredu** [comment]
> What version was this tested against? Most of this part was reworked in the latest commits.

0.0.45  nc 18.0.4

**Comment by Alexander-Zierhut** [comment]
I have had that too. Current version: 0.0.45 
@LukeLR This doesn't break anything though. A simple reload can be used as a workaround for now.

**Comment by smatthie** [comment]
This seems to be work correctly in version 0.48.

**Comment by Alexander-Zierhut** [comment]
Did not encounter it after updating either.
