### ISSUE TITLE
Installation of version 0.46 fails

### ISSUE THREAD

**Issue by smatthie** [mtierltd/timetracker#74]
Tried to update timetracker from the app store, and it resulted in blank views. The integrity check tells me that a lot of files are missing, see attached file.

[failed.txt](https://github.com/mtierltd/timetracker/files/5815423/failed.txt)

**Comment by reinerj** [comment]
Problem is solved. Please try again

**Comment by smatthie** [comment]
Yes, it works now, thanks.
