### ISSUE TITLE
Time Tracker 0.0.47: integrity check fails

### ISSUE THREAD

**Issue by AlterDepp** [mtierltd/timetracker#77]
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes
		- vendor/sebastian/recursion-context/.gitignore

Raw output
==========
Array
(
    [timetracker] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/phpunit/php-file-iterator/.gitattributes] => Array
                        (
                            [expected] => 66ca641a348a43ff13dc52eb690674319332d7eef2fc3dd03a3e1dad66c6375a2c6146e964591dd557d880cf89bedb10c4dd188b43582de7e96108028a541f54
                            [current] => 
                        )

                    [vendor/sebastian/recursion-context/.gitignore] => Array
                        (
                            [expected] => 7d6549d89864e9e1bea932f5624fd47df94594cc7d9cbf14ee18e217d63b839e8deba49024a4e6b899f906b58759540b29ac4dcb13af491a2a38477be4190c9b
                            [current] => 
                        )

                )

        )

)

**Comment by wm-lowe** [comment]
I have the same issue. I ran a check before upgrading from 20.0.4 with out a problem. Then after the upgrade to 20.0.5 completed, I, again ran a security check. it showed these two files missing.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes
		- vendor/sebastian/recursion-context/.gitignore

Raw output
==========
Array
(
    [timetracker] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/phpunit/php-file-iterator/.gitattributes] => Array
                        (
                            [expected] => 66ca641a348a43ff13dc52eb690674319332d7eef2fc3dd03a3e1dad66c6375a2c6146e964591dd557d880cf89bedb10c4dd188b43582de7e96108028a541f54
                            [current] => 
                        )

                    [vendor/sebastian/recursion-context/.gitignore] => Array
                        (
                            [expected] => 7d6549d89864e9e1bea932f5624fd47df94594cc7d9cbf14ee18e217d63b839e8deba49024a4e6b899f906b58759540b29ac4dcb13af491a2a38477be4190c9b
                            [current] => 
                        )

                )

        )

)

**Comment by laarisyko** [comment]
I get the exact same error with the same Nextcloud version. Is this issue critical of the App or Nextcloud?

**Comment by smatthie** [comment]
@laarisyko I'm not one of the developers, but I would say this error can be ignored. The files that are shown as missing are not files that carry any functionality in timetracker, but are config files for the repository which are only used by the developers. So presumably it's correct that they are not contained in the package on the app store, but their names got somehow listed in the integrity check.

**Comment by smatthie** [comment]
In 0.0.48, only one file (.gitattributes) fails the check now

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes

Raw output
==========
Array
(
    [timetracker] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/phpunit/php-file-iterator/.gitattributes] => Array
                        (
                            [expected] => 66ca641a348a43ff13dc52eb690674319332d7eef2fc3dd03a3e1dad66c6375a2c6146e964591dd557d880cf89bedb10c4dd188b43582de7e96108028a541f54
                            [current] => 
                        )

                )

        )

)

**Comment by wm-lowe** [comment]
I just upgraded to 0.0.49 and still show both files missing on Nextcloud 20.0.5 integrity check.

**Comment by AlterDepp** [comment]
Still fails on 0.0.50

**Comment by pongraczi** [comment]
The issue with NC 20.0.5 + TT 0.0.50  still exists.

```
Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes
		- vendor/sebastian/recursion-context/.gitignore

Raw output
==========
Array
(
    [timetracker] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/phpunit/php-file-iterator/.gitattributes] => Array
                        (
                            [expected] => 66ca641a348a43ff13dc52eb690674319332d7eef2fc3dd03a3e1dad66c6375a2c6146e964591dd557d880cf89bedb10c4dd188b43582de7e96108028a541f54
                            [current] => 
                        )

                    [vendor/sebastian/recursion-context/.gitignore] => Array
                        (
                            [expected] => 7d6549d89864e9e1bea932f5624fd47df94594cc7d9cbf14ee18e217d63b839e8deba49024a4e6b899f906b58759540b29ac4dcb13af491a2a38477be4190c9b
                            [current] => 
                        )

                )

        )

)
```

**Comment by smatthie** [comment]
Seems to be ok in 0.0.52

**Comment by AlterDepp** [comment]
Version 0.0.53 still fails.

**Comment by rnagy** [comment]
No, it does not.

`
$ php-7.3 occ app:install timetracker
timetracker 0.0.53 installed
timetracker enabled
$ php-7.3 occ integrity:check-app --path apps/timetracker -- timetracker                                                                                                                                                                 
$ echo $?
0
`

**Comment by pongraczi** [comment]
Sorry, I just upgraded to 0.0.53 with NC 20.0., the message still exists here.  

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes
		- vendor/sebastian/recursion-context/.gitignore

Raw output
==========
Array
(
    [timetracker] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/phpunit/php-file-iterator/.gitattributes] => Array
                        (
                            [expected] => 66ca641a348a43ff13dc52eb690674319332d7eef2fc3dd03a3e1dad66c6375a2c6146e964591dd557d880cf89bedb10c4dd188b43582de7e96108028a541f54
                            [current] => 
                        )

                    [vendor/sebastian/recursion-context/.gitignore] => Array
                        (
                            [expected] => 7d6549d89864e9e1bea932f5624fd47df94594cc7d9cbf14ee18e217d63b839e8deba49024a4e6b899f906b58759540b29ac4dcb13af491a2a38477be4190c9b
                            [current] => 
                        )
                )
        )
)
```

It is not a brand new installation as yours, but a continuously upgraded system.   

Just for the record, I copied my result for the same check command you used:  

```
# php7.3 occ integrity:check-app --path apps/timetracker -- timetracker 
An unhandled exception has been thrown:
ParseError: syntax error, unexpected 'BackupService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /path_to_nextcloud/apps/passwords/lib/Command/BackupCreateCommand.php:28
Stack trace:
#0 /path_to_nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/xxxx.x...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\Passwords\\C...')
#2 [internal function]: spl_autoload_call('OCA\\Passwords\\C...')
#3 /path_to_nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(107): ReflectionClass->__construct('OCA\\Passwords\\C...')
#4 /path_to_nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Passwords\\C...')
#5 /path_to_nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(455): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Passwords\\C...')
#6 /path_to_nextcloud/lib/private/ServerContainer.php(140): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Passwords\\C...')
#7 /path_to_nextcloud/lib/private/Console/Application.php(221): OC\ServerContainer->query('OCA\\Passwords\\C...')
#8 /path_to_nextcloud/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml(Array)
#9 /path_to_nextcloud/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /path_to_nextcloud/occ(11): require_once('/var/www/xxxx...')
#11 {main}root@hal9001:/var/www/xxxx.xxxx.hu/
```

It seems the brand new installation and an upgraded system behave differently.

**Comment by pongraczi** [comment]
After upgrading NC from 20.0.5 to 20.0.6 the original problem is gone (FILE_MISSING: - vendor/phpunit/php-file-iterator/.gitattributes  and  - vendor/sebastian/recursion-context/.gitignore)
