### ISSUE TITLE
In comibation with dark breeze theme some kind of objects are not readable

### ISSUE THREAD

**Issue by jenskaesler** [mtierltd/timetracker#78]
In comibation with dark breeze theme some kind of objects are not readable as you can see in the screenshot. Without using the theme all is looking perfect!

![image](https://user-images.githubusercontent.com/52004672/104886055-5d7f6400-5969-11eb-96e6-e3a6937db019.png)

Is there a chance to fix that? We are using dark breeze theme as system standard for all users. In earlier versions we had no issues with displaying these objects. This behavior exists since the last gui update.

Thanks in advance!

**Comment by reinerj** [comment]
Hi,

we are aware of this issue and it will be fixed soon.
