### ISSUE TITLE
interface to mobile

### ISSUE THREAD

**Issue by AETGH** [mtierltd/timetracker#8]
an interface to mobile phone Android would be great

**Comment by reinerj** [comment]
Can you explain a little more for what you are looking?

**Comment by AETGH** [comment]
i'm thinking if we should use it in the company for that you would have to be able to enter it via an additional interface browser or via mobile phone and also manage the users via nextcloud would be super nice

**Comment by reinerj** [comment]
Can you explain a little more how you want to manage the users over Nextcloud

**Comment by t2d** [comment]
Thank you for this nice app! It would be great if you could provide a more responsive layout to add data. That's the most important for me on mobile. Right now it's very difficult to do on a small device.

**Comment by AlterDepp** [comment]
It would be nice to start and stop the timer by an android app.
