### ISSUE TITLE
Using non-existent tag causes unrecoverable error

### ISSUE THREAD

**Issue by rhiaro** [mtierltd/timetracker#80]
I've been enjoying using this app to track everything for the past few days, and can see myself using it in the long term. But I just hit a bug that makes using it impossible to use, and I can't work out how to recover from it.

1. I started tagging entries I had already recorded. I typed a tag I thought I had already created but actually I hadn't, and the UI appeared to set it, then I got the popup "error getting work items", but nothing else changed.
2. I did **not** remove the mis-set tag.
3. I changed view, clicked around Reports and Timeline a bit, then went back to Timer and got the "error getting work items" and nothing else loaded.
4. I can't view or edit any entries for any time period that includes the entry with the mis-set tag (so I can't remove the bad tag). I can view entries from "today" because the entry with the bad tag is from yesterday, but not any bigger time period.

![Screenshot at 2021-01-21 10-38-01](https://user-images.githubusercontent.com/466229/105340471-d682f380-5bd5-11eb-8f25-fc6828334801.png)

Let me know if that isn't clear. Thanks!

(Related, if there was a full [import](https://github.com/mtierltd/timetracker/issues/50) ability I'd export, delete and reinstall the app, remove the bad entry from the data and re-import it and I'd be good.)

**Comment by puthre** [comment]
Can you see the logs on the server when you get this error message?

**Comment by puthre** [comment]
never mind, reproduced it.

**Comment by puthre** [comment]
New tags should be now created if they do not exist. It should also work if work items where somehow linked with tags that were not created.

**Comment by rhiaro** [comment]
Cheers! Excellent customer service, much appreciated :)

**Comment by rhiaro** [comment]
Sorry to bother you again, I don't have direct access to the server my nc instance is on so I can't swap the new code in, only update the app version. Do you know when you'll release an update with this fix?

**Comment by reinerj** [comment]
In the next days we will make a new release

**Comment by reinerj** [comment]
things change on the fly. We will make a new release today
