### ISSUE TITLE
Can't assign project to time entry

### ISSUE THREAD

**Issue by manfredu** [mtierltd/timetracker#85]
There are no projects to select although some do exist,

This is with version 0.5.

Two weeks or three weeks ago it still worked.

**Comment by manfredu** [comment]
OK, I need to add a user to the project. To be able to add a user I need to lock the project.

I thought unlocked project are not limited to any user, but they can't be used at all, as it looks like.

**Comment by puthre** [comment]
You probably are seeing projects that were not created by the current user (as you do when you are an admin). I know it's a bit non intuitive but you just need to add your current user to the project, best way is to just add a new project with the same name and it will link with the existing project.
