### ISSUE TITLE
old projects not showing up after color update (possibly due to not understanding what locked meant)

### ISSUE THREAD

**Issue by zeroepix** [mtierltd/timetracker#88]
When I try to assign a category to a timer, the project list drop-down is empty.

When I updated to 0.0.50 (from 0.0.46?), I went through my project list and added a color to each one individually. I didn't think much more of it until today where I discovered I can't add the category.

To try and diagnose it, I added a new 'test' one,  which worked fine and shows up in the project list, as the only one. The only difference I can see, is in the projects page this new 'test' project is the only one with myself as the "allowed users". The old ones are all blank in that field, and I can't seem to add myself to them in the UI.

I can probably fix this in the db directly, but maybe I won't be the only one that will have this issue.

**Comment by zeroepix** [comment]
I fixed this in the database by inserting a whole bunch of these:

insert into oc_timetracker_user_to_project (user_uid,project_id,admin,access,created_at) values ('username',1,1,1,1611711141);

But I see someone else had this issue too...I just had to add a project with the same name and it would have overwritten it? That may have worked fine if I'd seen that first.

**Comment by rhiaro** [comment]
+1 I just came here to leave the issue that when I edit a Project it loses the value of the 'allowed users' field and there is no way to edit that in the UI. I _think_ this is the same issue.
