### ISSUE TITLE
Delete projects

### ISSUE THREAD

**Issue by DecaTec** [mtierltd/timetracker#9]
Hello,

is there any way to delete a project?
I can edit a project, but I'm unable to delete it.

Am I missing something?

**Comment by reinerj** [comment]
There will be a function in a next release to archive a project.

**Comment by puthre** [comment]
Projects can now be archived.

**Comment by DecaTec** [comment]
Yes, can be archived now, but not deleted.
So archived projects remain in the cloud. A real delete of projects would be a nice feature.

**Comment by reinerj** [comment]
We will add the function that Admins can delete a project with all work items

**Comment by puthre** [comment]
Admins can now delete a project (with all the data attached)
3f2f9218dcb3d844eb48f0e1967deb27d6da0c0a
