### ISSUE TITLE
Cannot update to 0.0.51 and 0.0.52

### ISSUE THREAD

**Issue by AlterDepp** [mtierltd/timetracker#90]
When I want to update the app timetracker from 0.0.50 to 0.0.51 or now 0.0.52, I get an error that it is not possible. In the logs the message is »Error | core | Exception: Could not extract app timetracker«
All other apps work.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/25199 for context. The app apparently ships symlinks that are not allowed to be extracted. Drop them, rerelease and the extraction will work.

**Comment by reinerj** [comment]
New release is out which will fix this issue

**Comment by ChristophWurst** [comment]
On a side note you are also shipping dependency desp like phpunit. Consider stripping them.

**Comment by AlterDepp** [comment]
Thank you, 0.0.53 is working
