### ISSUE TITLE
integrity check failed again

### ISSUE THREAD

**Issue by EmJotGeh** [mtierltd/timetracker#92]
Hello,

Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes

Nextcloud: 20.0.6
Postgres SQL

Thank you for this useful NC App.

**Comment by devilsinkpot** [comment]
Same here. Uninstalled/installed two times, issue persists.

`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes`

**Comment by mtierltd** [comment]
I suggest that you remove the timetracker app and then make sure that the directory
is actually gone and there are no old files remaining there.

**Comment by devilsinkpot** [comment]
> I suggest that you remove the timetracker app and then make sure that the directory
> is actually gone and there are no old files remaining there.

I did – there is no timetracker-directory in /apps anymore. But the issue persists.

**Comment by mtierltd** [comment]
That is impossible because the latest release (0.0.53) does not have this file.

**Comment by EmJotGeh** [comment]
hello again, i can confirm that the issue persists. I delete the folder too and reinstall the time-tracker app again. The error was the same.

**Comment by Gunnar-GO** [comment]
The error says this **file is missing**.
To solve create one, it should be an empty file.

But, i don't get this error (updated timetracker on nextcloud 21, several instances), so maybe this bug report should marked as solved.
