### ISSUE TITLE
Lots of lag when changing/adding projects and tags in Timer view

### ISSUE THREAD

**Issue by rhiaro** [mtierltd/timetracker#97]
Since the 0.0.53 update, every time I choose a project or add a tag in the Timer view it hangs for several seconds before I can do anything else. Sometimes I get the "this webpage is slowing down your browser" bar for 1-2 seconds before it recovers. 

I'm using Firefox 85.0.1 on Ubuntu.

**Comment by puthre** [comment]
Duplicate of #35
